apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilist-fe-dev
  namespace: dev
spec:
  selector:
    matchLabels:
      app: cilist-fe-dev
  template:
    metadata:
      labels:
        app: cilist-fe-dev
    spec:
      containers:
      - name: cilist-fe-dev
        image: triagungtio/cilist-fe:{{NEW_TAG}}
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          value: https://dev-be.coffestory.de

---
apiVersion: v1
kind: Service
metadata:
  name: cilist-fe-dev
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: cilist-fe-dev
